### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HelgeSverre**
Added Guilty AS, which is the agency i work for, we do graphic design, websites and web applications, we use Craft as our CMS of choice.

### CODE REVIEW

**Comment by brandonkelly** [comment]
@bensomething @chrisrowe is there a criteria you guys were using for the Agencies section?

**Comment by HelgeSverre** [comment]
A criteria might be a good idea, what would one base those on though, size of the company, projects delivered, plugins made?

**Comment by bensomething** [comment]
Hmm, I had a feeling this section might become a little difficult to manage. I think the best idea would be to remove that section, as it doesn't _really_ showcase what Craft can do anyway.

**Comment by brandonkelly** [comment]
Yeah I think I agree.

**Pull request closed without merging**
